name: Respond to Dispatch Event

on:
  repository_dispatch:
    types: [trigger_event]  # Must match the event_type from Repo A

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "This workflow was triggered by a dispatch event"
